# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-14 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ['-c_time'], 'verbose_name': '节点', 'verbose_name_plural': '节点'},
        ),
    ]
