# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-14 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('supervisor', '0002_auto_20181114_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Police名字')),
                ('environment', models.TextField(verbose_name='环境(以;分割)')),
                ('type', models.TextField(verbose_name='功能(以;分割)')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('groups', models.ManyToManyField(to='auth.Group')),
                ('nodes', models.ManyToManyField(to='supervisor.Node')),
            ],
            options={
                'verbose_name': '节点',
                'verbose_name_plural': '节点',
                'ordering': ['-c_time'],
            },
        ),
    ]
