# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-14 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'ordering': ['-c_time'], 'verbose_name': '权限', 'verbose_name_plural': '权限'},
        ),
        migrations.AlterField(
            model_name='policy',
            name='environment',
            field=models.TextField(null=True, verbose_name='环境(以;分割)'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='type',
            field=models.TextField(null=True, verbose_name='功能(以;分割)'),
        ),
    ]
