# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-14 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_auto_20181114_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='environment',
            field=models.TextField(blank=True, null=True, verbose_name='环境(以;分割)'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='type',
            field=models.TextField(blank=True, null=True, verbose_name='功能(以;分割)'),
        ),
    ]
